In [1]:
import pandas as pd
df_xjjbsjxx = pd.read_csv('bks_xjjbsjxx_out.csv')

xh学号 yxsh院系所号 zym专业码 xkmlm学科门类码 pyfsm培养方式码 xslbm学生类别码
sznj所在年级 pyccm培养层次码 ldfsm连读方式码 xsdqztm学生当前状态码 sxccm学生层次码
szbh所在班号 rxny入学年月 sfyxj是否有学籍 sfygjxj是否有国家学籍 xqh校区号 ksh考生号
xz学制

In [2]:
df_xjjbsjxx

,xh,yxsh,zym,xkmlm,pyfsm,xslbm,sznj,pyccm,ldfsm,xsdqztm,xsccm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
0,201489089,308,7003,NaN,NaN,7,2014.0,NaN,NaN,7,NaN,软件1417,NaN,0,0,2.0,1.0
1,201539270,310,6403,8.0,NaN,6,2015.0,NaN,NaN,7,NaN,双外英1501,NaN,0,0,1.0,3.0
2,201559179,356,9111,8.0,NaN,6,2015.0,NaN,NaN,7,NaN,双管信1502,NaN,0,0,1.0,3.0
3,201539379,310,6403,8.0,NaN,6,2015.0,NaN,NaN,7,NaN,双外英1504,NaN,0,0,1.0,3.0
4,201529174,356,9111,8.0,NaN,6,2015.0,NaN,NaN,7,NaN,双管信1501,NaN,0,0,1.0,3.0
5,201549275,310,6403,8.0,NaN,6,2015.0,NaN,NaN,7,NaN,双外英1502,NaN,0,0,1.0,3.0
6,201459477,310,6403,NaN,NaN,6,2014.0,NaN,NaN,7,NaN,外英双1402,NaN,0,0,1.0,3.0
7,201479277,356,9111,NaN,NaN,6,2014.0,NaN,NaN,7,NaN,管信双1401,NaN,0,0,1.0,3.0
8,201429960,357,6301,NaN,NaN,5,2012.0,NaN,NaN,7,NaN,人文广1201,201503.0,0,0,1.0,1.0
9,201419473,310,6403,NaN,NaN,6,2014.0,NaN,NaN,7,NaN,外英双1401,NaN,0,0,1.0,3.0
10,201409579,310,6403,NaN,NaN,6,2014.0,NaN,NaN,7,NaN,外英双1403,NaN,0,0,1.0,3.0
11,201566010,305,5610,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,机制1507,201509.0,1,1,1.0,1.0
12,201524078,305,5610,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,机制1505,201509.0,1,1,1.0,1.0
13,201514097,301,5029,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,化高1501,201509.0,1,1,1.0,1.0
14,201515016,352,6110,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,土木1502,201509.0,1,1,1.0,1.0
15,201575014,352,6110,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,土木1503,201509.0,1,1,1.0,1.0
16,201555027,352,6101,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,土水1501,201509.0,1,1,1.0,1.0
17,201515126,352,6107,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,土港1502,201509.0,1,1,1.0,1.0
18,201525031,352,6112,12.0,NaN,1,2015.0,NaN,NaN,1,NaN,土管1501,201509.0,1,1,1.0,1.0
19,201555049,352,6131,8.0,NaN,1,2015.0,NaN,NaN,3,NaN,土交1501,201509.0,0,0,1.0,1.0
20,201505064,352,6115,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,国际土1501,201509.0,1,1,1.0,1.0
21,201525178,307,6201,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,建1502,201509.0,1,1,1.0,2.0
22,201505187,307,6210,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,建视1501,201509.0,1,1,1.0,1.0
23,201505099,301,5028,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,化药1501,201509.0,1,1,1.0,1.0
24,201418124,353,7806,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,电自1402,201409.0,0,0,1.0,1.0
25,201448035,353,7809,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,电通1402,201409.0,0,0,1.0,1.0
26,201418133,353,7809,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,电通1401,201409.0,0,0,1.0,1.0
27,201428042,353,7805,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,电集1402,201409.0,0,0,1.0,1.0
28,201408057,353,7807,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,电计1401,201409.0,0,1,1.0,1.0
29,201468059,353,7807,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,电计1401,201409.0,0,0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32450,201552092,912,980501,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,经济1502,201509.0,1,1,3.0,1.0
32451,201462065,914,980104,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,过控油1403,201409.0,1,1,3.0,1.0
32452,201772085,916,980403,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,运康1701,201709.0,1,1,3.0,1.0
32453,201739420,308,7002,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,软网1702,201709.0,1,1,2.0,1.0
32454,201756212,308,7003,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,软件1709,201709.0,1,1,2.0,1.0
32455,201734061,339,6901,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,环工1701,201709.0,1,1,1.0,1.0
32456,201714074,339,6901,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,环工1702,201709.0,1,1,1.0,1.0
32457,201871014,311,5203,NaN,NaN,1,2018.0,NaN,NaN,1,NaN,数华1801,201809.0,1,1,1.0,1.0
32458,201749083,311,5290,NaN,NaN,7,2017.0,NaN,NaN,1,NaN,数1702,201609.0,1,0,1.0,NaN
32459,201418075,353,7803,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,电计日1401,201409.0,1,1,1.0,2.0
32460,201425174,307,6201,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,建1402,201409.0,1,1,1.0,2.0
32461,201762334,363,981002,NaN,NaN,1,2017.0,NaN,NaN,3,NaN,应化国1701,201709.0,0,0,3.0,1.0
32462,201623066,912,980502,NaN,NaN,1,2016.0,NaN,NaN,1,NaN,人资1602,201609.0,1,1,3.0,1.0
32463,201482030,914,980101,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,应化1402,201409.0,1,1,3.0,1.0
32464,201562057,911,980602,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,过控海1501,201509.0,1,1,3.0,1.0
32465,201503007,912,980501,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,经济1501,201509.0,1,1,3.0,1.0
32466,201762442,913,980302,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,生信1701,201709.0,1,1,3.0,1.0
32467,201813061,912,980503,NaN,NaN,1,2018.0,NaN,NaN,1,NaN,电商1802,201809.0,1,1,3.0,1.0
32468,201764062,339,6901,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,环工1702,201709.0,1,1,1.0,1.0
32469,201749124,308,7003,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,软件1707,201709.0,1,1,2.0,1.0
32470,201679089,308,7003,NaN,NaN,7,2016.0,NaN,NaN,1,NaN,软件1617,201609.0,1,0,NaN,NaN
32471,201413087,912,980502,NaN,NaN,1,2014.0,NaN,NaN,7,NaN,人资1402,201409.0,0,0,3.0,1.0
32472,201409327,307,6201,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,建1402,201409.0,1,1,1.0,2.0
32473,201415272,307,6209,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,建规1401,201409.0,1,1,1.0,2.0
32474,201673058,912,980501,NaN,NaN,1,2016.0,NaN,NaN,1,NaN,经济1602,201609.0,1,1,3.0,1.0
32475,201643024,912,980501,NaN,NaN,1,2016.0,NaN,NaN,1,NaN,经济1601,201609.0,1,1,3.0,1.0
32476,201523063,912,980502,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,人资1502,201509.0,1,1,3.0,1.0
32477,201553088,911,980601,8.0,NaN,1,2015.0,NaN,NaN,1,NaN,海技1501,201509.0,1,1,3.0,1.0
32478,201453069,915,980201,NaN,NaN,1,2014.0,NaN,NaN,1,NaN,食品1401,201409.0,1,1,3.0,1.0
32479,201772092,912,980501,NaN,NaN,1,2017.0,NaN,NaN,1,NaN,经济1702,201709.0,1,1,3.0,1.0

In [3]:
df_xjjbsjxx.isnull().sum()

xh             0
yxsh           0
zym            0
xkmlm      25823
pyfsm      32480
xslbm          0
sznj           3
pyccm      32470
ldfsm      32480
xsdqztm        0
xsccm      32480
szbh          31
rxny         906
sfyxj          0
sfygjxj        0
xqh           38
xz           145
dtype: int64

In [4]:
xjjbsjxx_pyfsm = df_xjjbsjxx[df_xjjbsjxx['pyfsm'].isnull()]

In [5]:
xjjbsjxx_pyccm = df_xjjbsjxx[df_xjjbsjxx['pyccm'].isnull()]

In [6]:
xjjbsjxx_ldfsm = df_xjjbsjxx[df_xjjbsjxx['ldfsm'].isnull()]

In [7]:
xjjbsjxx_xsccm = df_xjjbsjxx[df_xjjbsjxx['xsccm'].isnull()]

In [8]:
xjjbsjxx_xkmlm = df_xjjbsjxx[df_xjjbsjxx['xkmlm'].isnull()]

pyfsm pyccm ldfsm xsccm xkmlm这5项基本都为空，可以去掉

In [9]:
xjjbsjxx_sznj = df_xjjbsjxx[df_xjjbsjxx['sznj'].isnull()]
df_xjjbsjxx['sznj'].isnull().sum()

3

所在年级可以确定当前年级，缺失值用学号确定

In [10]:
xjjbsjxx_sznj

,xh,yxsh,zym,xkmlm,pyfsm,xslbm,sznj,pyccm,ldfsm,xsdqztm,xsccm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
685,201449061,350,10001,NaN,NaN,5,NaN,NaN,NaN,7,NaN,NaN,NaN,0,0,NaN,1.0
1296,201749067,350,10001,NaN,NaN,5,NaN,NaN,NaN,1,NaN,NaN,201709.0,1,0,1.0,1.0
4645,201449064,350,10001,NaN,NaN,5,NaN,NaN,NaN,7,NaN,NaN,NaN,0,0,NaN,1.0

In [11]:
for i in df_xjjbsjxx.index:
    df_xjjbsjxx.sznj = df_xjjbsjxx.xh // 100000

In [12]:
df_xjjbsjxx.sznj.isnull().sum()

0

所在年级已经补齐，根据学号的前4位

In [13]:
xjjbsjxx_rxny=df_xjjbsjxx[df_xjjbsjxx['rxny'].isnull()]

In [14]:
df_xjjbsjxx['rxny'].isnull().sum()

906

906个入学年份空数据，入学年份根据所在年级确定，入学年月=所在年级*100+9

In [15]:
for i in df_xjjbsjxx.index:
     df_xjjbsjxx.rxny= df_xjjbsjxx.sznj*100 + 9

In [16]:
df_xjjbsjxx['rxny'].isnull().sum()

0

入学年份0个空数据，已补齐

In [17]:
xjjbsjxx_xqh=df_xjjbsjxx[df_xjjbsjxx['xqh'].isnull()]

In [18]:
df_xjjbsjxx['xqh'].isnull().sum()

38

校区号根据专业码确定，0~6999为1.0，7000多为2.0，980000多为3.0

In [19]:
for i in df_xjjbsjxx.index:
    if df_xjjbsjxx.loc[i,'zym'] < 7000:
        df_xjjbsjxx.xqh = 1.0
    elif df_xjjbsjxx.loc[i,'zym'] < 8000:
        df_xjjbsjxx.xqh = 2.0
    elif df_xjjbsjxx.loc[i,'zym'] >= 8000:
        df_xjjbsjxx.xqh = 3.0

In [20]:
df_xjjbsjxx['xqh'].isnull().sum()

0

校区号全部补齐，根据相关专业只在特定校区开设

In [21]:
xjjbsjxx_szbh=df_xjjbsjxx[df_xjjbsjxx['szbh'].isnull()]

In [22]:
df_xjjbsjxx['szbh'].isnull().sum()

31

In [23]:
xjjbsjxx_szbh.sample(5)

,xh,yxsh,zym,xkmlm,pyfsm,xslbm,sznj,pyccm,ldfsm,xsdqztm,xsccm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
17228,201419060,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,NaN,201409,0,0,3.0,1.0
901,201739067,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,NaN,201709,1,0,3.0,1.0
15210,201569062,350,10001,8.0,NaN,5,2015,NaN,NaN,1,NaN,NaN,201509,1,0,3.0,1.0
3998,201749060,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,NaN,201709,1,0,3.0,1.0
16184,201489066,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,NaN,201409,0,0,3.0,1.0

In [24]:
for i in xjjbsjxx_szbh.index:
    xjjbsjxx_szbh.loc[i,'szbh']= 'hyy'+ str((xjjbsjxx_szbh.loc[i,'sznj']-2000)*100+1)

C:\Users\Marc\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

这里所有缺失班号的同学，都是hyy专业的，就想直接用hyy+所在年级（比如1401 1501 1601 1701 1801）来确定

In [25]:
xjjbsjxx_szbh

,xh,yxsh,zym,xkmlm,pyfsm,xslbm,sznj,pyccm,ldfsm,xsdqztm,xsccm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
685,201449061,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
796,201749066,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
901,201739067,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
1296,201749067,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
3004,201729068,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
3919,201429062,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
3998,201749060,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
4443,201419063,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
4645,201449064,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
4940,201739069,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
5019,201739068,350,10001,NaN,NaN,5,2017,NaN,NaN,1,NaN,hyy1701,201709,1,0,3.0,1.0
5046,201709965,350,10001,NaN,NaN,5,2017,NaN,NaN,7,NaN,hyy1701,201709,0,0,3.0,1.0
5653,201679066,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
5808,201679064,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
6175,201669065,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
6196,201679065,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
6302,201689060,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
6564,201669064,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
8314,201679068,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
8808,201679069,350,10001,NaN,NaN,5,2016,NaN,NaN,7,NaN,hyy1601,201609,0,0,3.0,1.0
9615,201679062,350,10001,NaN,NaN,5,2016,NaN,NaN,7,NaN,hyy1601,201609,0,0,3.0,1.0
10109,201609066,350,10001,NaN,NaN,5,2016,NaN,NaN,1,NaN,hyy1601,201609,1,0,3.0,1.0
14696,201519063,350,10001,8.0,NaN,5,2015,NaN,NaN,1,NaN,hyy1501,201509,1,0,3.0,1.0
15210,201569062,350,10001,8.0,NaN,5,2015,NaN,NaN,1,NaN,hyy1501,201509,1,0,3.0,1.0
15470,201449062,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
16184,201489066,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
16336,201489064,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
16984,201529064,350,10001,8.0,NaN,5,2015,NaN,NaN,1,NaN,hyy1501,201509,1,0,3.0,1.0
17228,201419060,350,10001,NaN,NaN,5,2014,NaN,NaN,7,NaN,hyy1401,201409,0,0,3.0,1.0
17752,201519067,350,10001,8.0,NaN,5,2015,NaN,NaN,1,NaN,hyy1501,201509,1,0,3.0,1.0
19506,201519064,350,10001,8.0,NaN,5,2015,NaN,NaN,7,NaN,hyy1501,201509,0,0,3.0,1.0

In [26]:
xjjbsjxx_szbh['szbh'].isnull().sum()

0

这里所有缺失班号的同学，都把班号补上了，由于具体班级无从得知，暂且都放在该届的1班

In [27]:
xjjbsjxx_xz = df_xjjbsjxx[df_xjjbsjxx['xz'].isnull()]

In [28]:
df_xjjbsjxx.xz.isnull().sum()

145

有145人的学制信息丢失

In [29]:
xjjbsjxx_xz

,xh,yxsh,zym,xkmlm,pyfsm,xslbm,sznj,pyccm,ldfsm,xsdqztm,xsccm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
64,201739081,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1705,201709,1,0,3.0,NaN
169,201729086,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1702,201709,1,0,3.0,NaN
382,201719083,353,7808,NaN,NaN,7,2017,NaN,NaN,1,NaN,电信1701,201709,1,0,3.0,NaN
483,201739089,317,5890,NaN,NaN,7,2017,NaN,NaN,1,NaN,动1702,201709,1,0,3.0,NaN
564,201739080,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1704,201709,1,0,3.0,NaN
665,201709081,352,6112,NaN,NaN,7,2017,NaN,NaN,1,NaN,土管1701,201709,1,0,3.0,NaN
669,201739088,317,5890,NaN,NaN,7,2017,NaN,NaN,1,NaN,动1701,201709,1,0,3.0,NaN
799,201709088,353,7801,NaN,NaN,7,2017,NaN,NaN,1,NaN,电医1701,201709,1,0,3.0,NaN
1090,201709089,353,7801,NaN,NaN,7,2017,NaN,NaN,1,NaN,电医1701,201709,1,0,3.0,NaN
1194,201719082,353,7807,NaN,NaN,7,2017,NaN,NaN,1,NaN,电计1701,201709,1,0,3.0,NaN
1300,201729087,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1703,201709,1,0,3.0,NaN
1717,201759990,917,980901,NaN,NaN,6,2017,3.0,NaN,1,NaN,知产1701,201709,1,0,3.0,NaN
1902,201719081,353,7807,NaN,NaN,7,2017,NaN,NaN,1,NaN,电计1701,201709,1,0,3.0,NaN
1981,201719088,311,5290,NaN,NaN,7,2017,NaN,NaN,1,NaN,数1705,201709,1,0,3.0,NaN
2112,201729084,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1701,201709,1,0,3.0,NaN
2189,201709083,310,6401,NaN,NaN,7,2017,NaN,NaN,1,NaN,外英语1701,201709,1,0,3.0,NaN
2374,201709084,301,5008,NaN,NaN,7,2017,NaN,NaN,1,NaN,化1701,201709,1,0,3.0,NaN
2427,201719089,311,5290,NaN,NaN,7,2017,NaN,NaN,1,NaN,数1705,201709,1,0,3.0,NaN
2507,201729085,352,6191,NaN,NaN,7,2017,NaN,NaN,1,NaN,土水类1702,201709,1,0,3.0,NaN
2527,201709082,353,7808,NaN,NaN,7,2017,NaN,NaN,1,NaN,电信1701,201709,1,0,3.0,NaN
2610,201739082,351,7901,NaN,NaN,7,2017,NaN,NaN,1,NaN,运船1701,201709,1,0,3.0,NaN
2636,201739083,351,7901,NaN,NaN,7,2017,NaN,NaN,1,NaN,运船1702,201709,1,0,3.0,NaN
2715,201719080,317,5890,NaN,NaN,7,2017,NaN,NaN,1,NaN,动1701,201709,1,0,3.0,NaN
2901,201749080,305,5690,NaN,NaN,7,2017,NaN,NaN,1,NaN,机1701,201709,1,0,3.0,NaN
3424,201739085,352,6110,NaN,NaN,7,2017,NaN,NaN,1,NaN,土木1701,201709,1,0,3.0,NaN
3528,201719087,340,7602,NaN,NaN,7,2017,NaN,NaN,1,NaN,生1702,201709,1,0,3.0,NaN
3609,201719086,340,7602,NaN,NaN,7,2017,NaN,NaN,1,NaN,生1701,201709,1,0,3.0,NaN
3976,201709087,311,5290,NaN,NaN,7,2017,NaN,NaN,1,NaN,数1705,201709,1,0,3.0,NaN
4001,201709086,301,5021,NaN,NaN,7,2017,NaN,NaN,1,NaN,化应1701,201709,1,0,3.0,NaN
4130,201709085,301,5008,NaN,NaN,7,2017,NaN,NaN,1,NaN,化1701,201709,1,0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31656,201669088,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
31678,201819062,350,10001,NaN,NaN,5,2018,NaN,NaN,1,NaN,hyy1801,201809,1,0,3.0,NaN
31709,201809068,350,10001,NaN,NaN,5,2018,NaN,NaN,1,NaN,hyy1801,201809,1,0,3.0,NaN
31753,201669085,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
31776,201839063,307,629001,NaN,NaN,5,2018,NaN,NaN,1,NaN,建1801,201809,1,0,3.0,NaN
31879,201819960,357,6390,NaN,NaN,5,2018,NaN,NaN,1,NaN,人传类1801,201809,1,0,3.0,NaN
31889,201669084,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
31926,201679088,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32023,201829067,352,6110,NaN,NaN,5,2018,NaN,NaN,1,NaN,建土1801,201809,1,0,3.0,NaN
32034,201529194,305,5610,NaN,NaN,7,2015,NaN,NaN,1,NaN,机制1501,201509,1,0,3.0,NaN
32053,201839061,307,629001,NaN,NaN,5,2018,NaN,NaN,1,NaN,建1801,201809,1,0,3.0,NaN
32064,201819067,301,5003,NaN,NaN,5,2018,NaN,NaN,7,NaN,国际化1801,201809,0,0,3.0,NaN
32076,201689080,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32117,201819065,350,10001,NaN,NaN,5,2018,NaN,NaN,1,NaN,hyy1701,201809,1,0,3.0,NaN
32136,201763041,917,980901,NaN,NaN,6,2017,3.0,NaN,1,NaN,知产1701,201709,1,0,3.0,NaN
32153,201839060,307,629001,NaN,NaN,5,2018,NaN,NaN,1,NaN,建1801,201809,1,0,3.0,NaN
32184,201829066,352,6110,NaN,NaN,5,2018,NaN,NaN,1,NaN,建土1801,201809,1,0,3.0,NaN
32202,201689083,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32225,201809066,356,9110,NaN,NaN,5,2018,NaN,NaN,1,NaN,管经1804,201809,1,0,3.0,NaN
32236,201619197,305,5610,NaN,NaN,7,2016,NaN,NaN,1,NaN,机制1601,201609,1,0,3.0,NaN
32273,201679080,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32330,201829064,305,5627,NaN,NaN,5,2018,NaN,NaN,1,NaN,国际机1801,201809,1,0,3.0,NaN
32365,201819066,350,10001,NaN,NaN,5,2018,NaN,NaN,1,NaN,hyy1801,201809,1,0,3.0,NaN
32376,201519199,356,9106,NaN,NaN,7,2015,NaN,NaN,1,NaN,经贸1501,201509,1,0,3.0,NaN
32377,201749082,312,530502,NaN,NaN,7,2017,NaN,NaN,1,NaN,物1701,201709,1,0,3.0,NaN
32417,201519198,356,9109,NaN,NaN,7,2015,NaN,NaN,1,NaN,经金1501,201509,1,0,3.0,NaN
32430,201679081,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32443,201669086,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN
32458,201749083,311,5290,NaN,NaN,7,2017,NaN,NaN,1,NaN,数1702,201709,1,0,3.0,NaN
32470,201679089,308,7003,NaN,NaN,7,2016,NaN,NaN,1,NaN,软件1617,201609,1,0,3.0,NaN

观察发现，学制信息丢失的学生，xslbm为5，6，或者7。xslbm为5或者7的同学学制均为1.0。xslbm为6的同学学制均为3.0

In [30]:
for i in df_xjjbsjxx.index:
    if df_xjjbsjxx.loc[i,'xslbm'] == 7:
        df_xjjbsjxx.xz = 1.0
    elif df_xjjbsjxx.loc[i,'xslbm'] == 5:
        df_xjjbsjxx.xz = 1.0
    elif df_xjjbsjxx.loc[i,'xslbm'] == 6:
        df_xjjbsjxx.xz = 3.0

In [31]:
df_xjjbsjxx.xz.isnull().sum()

0

学制信息全部补齐

In [32]:
for i in df_xjjbsjxx.index:
    if df_xjjbsjxx.loc[i,'zym'] == 10001:
        df_xjjbsjxx.loc[i,'szbh']= 'hyy'+ str((df_xjjbsjxx.loc[i,'sznj']-2000)*100+1)

将在xjjbsjxx_szbh这个dataframe中补充的班号添加到原来的df_xjjbsjxx这个dataframe中

In [33]:
df_roll = df_xjjbsjxx.copy()

In [34]:
df_roll.drop(columns=['xkmlm','pyfsm','pyccm','ldfsm','xsccm'],inplace=True)

In [35]:
df_roll.isnull().sum()

xh         0
yxsh       0
zym        0
xslbm      0
sznj       0
xsdqztm    0
szbh       0
rxny       0
sfyxj      0
sfygjxj    0
xqh        0
xz         0
dtype: int64

In [36]:
df_roll.head(2)

,xh,yxsh,zym,xslbm,sznj,xsdqztm,szbh,rxny,sfyxj,sfygjxj,xqh,xz
0,201489089,308,7003,7,2014,7,软件1417,201409,0,0,3.0,1.0
1,201539270,310,6403,6,2015,7,双外英1501,201509,0,0,3.0,1.0

In [37]:
df_roll['xsdqztm'].value_counts()

1     25665
7      6553
3       261
10        1
Name: xsdqztm, dtype: int64

In [39]:
roll = df_roll[['xh','yxsh','zym','sznj']]

In [40]:
roll.to_csv('roll.csv',encoding='utf-8',index=False)